USE [master]
GO
/****** Object:  Database [Ordering]    Script Date: 7/22/2020 9:13:08 AM ******/
CREATE DATABASE [Ordering]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ordering', FILENAME = N'/var/opt/mssql/data/Ordering.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ordering_log', FILENAME = N'/var/opt/mssql/data/Ordering_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Ordering] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ordering].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Ordering] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Ordering] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Ordering] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Ordering] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Ordering] SET ARITHABORT OFF 
GO
ALTER DATABASE [Ordering] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Ordering] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Ordering] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Ordering] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Ordering] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Ordering] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Ordering] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Ordering] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Ordering] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Ordering] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Ordering] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Ordering] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Ordering] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Ordering] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Ordering] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Ordering] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Ordering] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Ordering] SET RECOVERY FULL 
GO
ALTER DATABASE [Ordering] SET  MULTI_USER 
GO
ALTER DATABASE [Ordering] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Ordering] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Ordering] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Ordering] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Ordering] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Ordering', N'ON'
GO
ALTER DATABASE [Ordering] SET QUERY_STORE = OFF
GO
USE [Ordering]
GO
/****** Object:  Table [dbo].[Buyer]    Script Date: 7/22/2020 9:13:08 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Buyer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
 CONSTRAINT [PK_Buyer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Order]    Script Date: 7/22/2020 9:13:08 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Date] [datetime] NOT NULL,
	[BuyerId] [int] NOT NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderItem]    Script Date: 7/22/2020 9:13:08 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderItem](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[Quantity] [int] NOT NULL,
	[OrderId] [int] NOT NULL,
 CONSTRAINT [PK_OrderItem] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_Order_Buyer] FOREIGN KEY([BuyerId])
REFERENCES [dbo].[Buyer] ([Id])
GO
ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_Order_Buyer]
GO
ALTER TABLE [dbo].[OrderItem]  WITH CHECK ADD  CONSTRAINT [FK_OrderItem_Order] FOREIGN KEY([OrderId])
REFERENCES [dbo].[Order] ([Id])
GO
ALTER TABLE [dbo].[OrderItem] CHECK CONSTRAINT [FK_OrderItem_Order]
GO
USE [master]
GO
ALTER DATABASE [Ordering] SET  READ_WRITE 
GO
